// Speaking niches and their topics
export const NICHES = [
  {
    id: 'tech',
    name: 'Tech & Innovation',
    icon: '💻',
    color: '#6366f1',
    description: 'Startups, AI, software & future of tech',
    topics: [
      'Explain blockchain to a 10-year-old',
      'Pitch your AI startup idea in 90 seconds',
      'Why every job will require coding skills by 2030',
      'The ethical dilemmas of artificial general intelligence',
      'How open-source software changed the world',
      'The rise of quantum computing — what it means for us',
      'Why cybersecurity is the biggest unsolved problem of our time',
      'The metaverse: hype or the future of human connection?',
      'How I would redesign the internet from scratch',
      'Automation and the future of employment',
    ],
  },
  {
    id: 'business',
    name: 'Business & Leadership',
    icon: '📈',
    color: '#0ea5e9',
    description: 'Strategy, negotiation & entrepreneurship',
    topics: [
      'The art of negotiation — lessons from the boardroom',
      'Why remote teams will outperform office teams by 2030',
      'How to build a brand people actually care about',
      'The secret to scaling a business without losing culture',
      'Three things every great leader does differently',
      'Why small bets beat big plans in business',
      'How I would turn around a failing company in 90 days',
      'The case for hiring people smarter than you',
      'Why failure is the best business school',
      'Customer obsession vs. product obsession — which wins?',
    ],
  },
  {
    id: 'motivational',
    name: 'Motivational',
    icon: '🔥',
    color: '#f97316',
    description: 'Inspiration, mindset & personal growth',
    topics: [
      'Your biggest failure made you who you are today',
      'One habit that completely changed my life',
      'Why comfort is the enemy of growth',
      'The day I decided to stop making excuses',
      'How to build unshakeable confidence from scratch',
      'The power of saying no to the right things',
      'Why the hardest path is always the right path',
      'What I wish I knew at 20 about resilience',
      'The science of motivation — why willpower is a myth',
      'You are one decision away from a completely different life',
    ],
  },
  {
    id: 'storytelling',
    name: 'Storytelling',
    icon: '📖',
    color: '#ec4899',
    description: 'Personal narratives & creative expression',
    topics: [
      'The day I almost quit — and what stopped me',
      'A stranger who changed the course of my life',
      'The moment I realized I was wrong about everything',
      'A lesson I learned too late and too painfully',
      'The best advice I ever received — and ignored',
      'A childhood memory that still shapes my decisions',
      'The bravest thing I have ever done',
      'A conversation that broke me open',
      'The time I had to choose between two lives',
      'What my biggest mistake taught me about grace',
    ],
  },
  {
    id: 'educational',
    name: 'Educational',
    icon: '🧠',
    color: '#10b981',
    description: 'Science, psychology & how the world works',
    topics: [
      'How the human brain actually learns new things',
      'Why sleep is the most underrated performance tool',
      'The psychology of habit formation — and how to hack it',
      'What evolution got wrong about the modern world',
      'The surprising science behind decision fatigue',
      'How language shapes the way we think and feel',
      'Why everything you know about nutrition is probably wrong',
      'The hidden math behind everyday coincidences',
      'How emotions are constructed — not felt',
      'The real reason why most people never achieve their goals',
    ],
  },
];

export const getNicheById = (id) => NICHES.find((n) => n.id === id);
